services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data-batch:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  postgres-data-batch:
    name: postgres-data-batch